
function safeSetInnerHTML(elementId, innerHTMLContent) {
    const element = document.getElementById(elementId);
    if (element) {
        element.innerHTML = innerHTMLContent;
    } else {
        console.warn(`Element with ID '${elementId}' not found.`);
    }
}

safeSetInnerHTML("btb_title_1", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 790-800: Completing Tailgate and Rearview Mirror</h1></div>`);
safeSetInnerHTML("btb_icon_1_1", `<div class="icon-container"><i class="fas fa-layer-group"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_icon_1_2", `<div class="icon-container"><i class="fas fa-clock"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_maintext_1", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this final stage, we complete the <strong>tailgate assembly</strong> and add the <strong>rearview mirror</strong>. The origins of the G-Class trace back to a proposal from the <strong>Shah of Iran</strong> in the early 1970s. A major shareholder in Mercedes-Benz, the Shah suggested creating a durable, off-road military vehicle, which led to the development of the G-Class.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">The G-Class was initially marketed under the <strong>Puch brand</strong> in Austria and some Eastern European countries due to the collaboration with Steyr-Daimler-Puch. This durable, versatile vehicle was officially launched in 1979 and quickly gained popularity across global markets, transforming from a military icon into a luxury off-road vehicle.</p></div>`);
safeSetInnerHTML("btb_image_1", `<img src="https://github.com/behind-the-builds/btb/g500/images/Puch_300GD_Serbian_military_3.jpg" alt="A Serbian military Puch G-Class">`);
safeSetInnerHTML("btb_caption_1", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">A Serbian military Puch G-Class</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:Puch_300GD_Serbian_military_3.jpg" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_2", `<div class="title-container"><h1 style="white-space:pre-wrap;">Bag 19: External Accessories</h1></div>`);
safeSetInnerHTML("btb_icon_2_1", `<div class="icon-container"><i class="fas fa-globe"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_icon_2_2", `<div class="icon-container"><i class="fas fa-box"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_maintext_2", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In Bag 19, we add several <strong>external accessories</strong> to our G-Class model: the roof steerer, spare tire, top storage bin, mud flaps, and a rear bar. While the roof steerer enhances playability, the tailgate-mounted spare tire mirrors the real G-Class design, balancing accessibility with practicality. The top storage bin adds functional utility, and the rear bar protects the spare and back area. These accessories enhance both play and realism, echoing the G-Class’s practical, rugged heritage.</p></div>`);
safeSetInnerHTML("btb_image_2", `<img src="https://github.com/behind-the-builds/btb/g500/images/Canadian_Land_Forces_Mercedes-Benz_G-Class.JPG" alt="A convoy of military G-Class vehicles">`);
safeSetInnerHTML("btb_caption_2", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">A convoy of military G-Class vehicles</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:Canadian_Land_Forces_Mercedes-Benz_G-Class.JPG" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_3", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 801-803: Roof Steerer and Spare Tire</h1></div>`);
safeSetInnerHTML("btb_icon_3_1", `<div class="icon-container"><i class="fas fa-wrench"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_icon_3_2", `<div class="icon-container"><i class="fas fa-circle"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_maintext_3", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this section, we add the <strong>roof steerer</strong> (to control the model’s front wheels) and mount the <strong>spare tire</strong> on the tailgate. This exterior mounting keeps interior space available and ensures easy access in rugged conditions. The tailgate’s side-opening design also accommodates the tire’s weight, which would be cumbersome if mounted on a roof or trunk, making it a practical and iconic feature of the G-Class.</p></div>`);
safeSetInnerHTML("btb_image_3", `<img src="https://github.com/behind-the-builds/btb/g500/images/MP-ISAF.jpg" alt="A G-Class in German MP service">`);
safeSetInnerHTML("btb_caption_3", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">A G-Class in German MP service</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:MP-ISAF.jpg" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_4", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 804-819: Top Storage Bin</h1></div>`);
safeSetInnerHTML("btb_icon_4_1", `<div class="icon-container"><i class="fas fa-door-open"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_icon_4_2", `<div class="icon-container"><i class="fas fa-box"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_maintext_4", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">Here we add the <strong>top storage bin</strong>, inspired by the real G-Class’s <strong>Professional Line</strong> options. In adventure-ready models, the top storage compartment is ideal for stowing extra equipment without taking up rear cargo space. This feature enhances the G-Class’s versatility in both off-road and urban environments.</p></div>`);
safeSetInnerHTML("btb_title_5", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 820-823: Mud Flaps</h1></div>`);
safeSetInnerHTML("btb_icon_5_1", `<div class="icon-container"><i class="fas fa-box"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_icon_5_2", `<div class="icon-container"><i class="fas fa-tint"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_maintext_5", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this step, we add <strong>mud flaps</strong> to the model. Designed to protect the vehicle’s undercarriage from mud, rocks, and debris, mud flaps are essential for maintaining the vehicle’s durability, especially during off-road travel. The G-Class mud flaps are constructed from reinforced materials, ensuring longevity and keeping the vehicle’s body panels safe from damage on rough terrain.</p></div>`);
