
function safeSetInnerHTML(elementId, innerHTMLContent) {
    const element = document.getElementById(elementId);
    if (element) {
        element.innerHTML = innerHTMLContent;
    } else {
        console.warn(`Element with ID '${elementId}' not found.`);
    }
}

safeSetInnerHTML("btb_title_1", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 628-727: Side Wall Assembly</h1></div>`);
safeSetInnerHTML("btb_icon_1_1", `<div class="icon-container"><i class="fas fa-shield-alt"></i></div><div class="title-container">Armored Protection</div><div class="content-container">Reinforced with ballistic materials, ensuring safety for high-risk missions.</div>`);
safeSetInnerHTML("btb_icon_1_2", `<div class="icon-container"><i class="fas fa-box"></i></div><div class="title-container">Secure Cargo Space</div><div class="content-container">Built for heavy-duty use, with armored models adding top-level security.</div>`);
safeSetInnerHTML("btb_maintext_1", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this stage, we build the <strong>side walls of the cargo area</strong>, completing a key structural component of the G-Class model. These side walls echo the real G-Class’s rugged cargo area, which can be customized with armored options. For example, in bulletproof G-Class models, reinforced steel, multi-layer ballistic glass, and specialized run-flat tires create a secure cabin capable of withstanding ballistic threats.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">Armored versions of the G-Class are designed to support security missions in urban and remote areas alike. Features like the armored cargo side panels provide essential protection for transporting valuable equipment and supplies, ensuring safety without sacrificing the vehicle’s luxury or performance.</p></div>`);
safeSetInnerHTML("btb_image_1", `<img src="https://github.com/behind-the-builds/btb/g500/images/Mercedes_Benz_G._Trasco._Spielvogel1.jpg" alt="An armored G-Class by Trasco">`);
safeSetInnerHTML("btb_caption_1", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">An armored G-Class by Trasco</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:Mercedes_Benz_G._Trasco._Spielvogel1.jpg" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_2", `<div class="title-container"><h1 style="white-space:pre-wrap;">Bag 17: Rear Tailgate, Wheel Well Trim, and Door Steps</h1></div>`);
safeSetInnerHTML("btb_icon_2_1", `<div class="icon-container"><i class="fas fa-box"></i></div><div class="title-container">Functional Cargo Access</div><div class="content-container">Tailgate and steps provide accessible entry and cargo storage, designed for rugged use.</div>`);
safeSetInnerHTML("btb_icon_2_2", `<div class="icon-container"><i class="fas fa-globe"></i></div><div class="title-container">Built for Tough Terrain</div><div class="content-container">Door steps and trim enhance utility, easing access in rugged or lifted vehicles.</div>`);
safeSetInnerHTML("btb_maintext_2", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In Bag 17, we assemble the <strong>rear tailgate</strong>, along with <strong>wheel well trim</strong> and <strong>door steps</strong>. These elements are designed for durability and practical function, providing essential access, protection, and clearance for rugged environments. The door steps help ease entry, especially in lifted G-Class models, while the tailgate offers versatile access to the rear cargo space. In real-world applications, the G-Class’s robust tailgate is crucial for quick cargo loading in harsh conditions, reflecting the vehicle’s legacy of utility in challenging terrains.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">The G-Class’s functional design has been instrumental in mountain rescues and special operations. Used by teams like Germany's Bad Kohlgrub mountain rescue, it offers easy access for transporting equipment in difficult landscapes.</p></div>`);
safeSetInnerHTML("btb_image_2", `<img src="https://github.com/behind-the-builds/btb/g500/images/Mercedes_Benz_GD_in_Lithuanian_service.jpg" alt="G-Class in Lithuanian service">`);
safeSetInnerHTML("btb_caption_2", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">G-Class in Lithuanian service</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:Mercedes_Benz_GD_in_Lithuanian_service.jpg" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_3", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 728-739: Wheel Well Trim and Door Steps</h1></div>`);
safeSetInnerHTML("btb_icon_3_1", `<div class="icon-container"><i class="fas fa-shoe-prints"></i></div><div class="title-container">Enhanced Accessibility</div><div class="content-container">Door steps make entry easier, especially valuable in rugged or lifted G-Class models.</div>`);
safeSetInnerHTML("btb_icon_3_2", `<div class="icon-container"><i class="fas fa-shield-alt"></i></div><div class="title-container">Protective Trim</div><div class="content-container">Wheel well trim guards against debris, maintaining durability in off-road settings.</div>`);
safeSetInnerHTML("btb_maintext_3", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this section, we attach the <strong>wheel well trim</strong> and <strong>door steps</strong>. The wheel well trim provides clearance and protects the body from debris, essential in off-road conditions. The door steps, or running boards, make it easier to enter and exit the vehicle, especially useful for lifted G-Class models or rough terrain. These components enhance usability without compromising the G-Class’s rugged appearance.</p></div>`);
