
function safeSetInnerHTML(elementId, innerHTMLContent) {
    const element = document.getElementById(elementId);
    if (element) {
        element.innerHTML = innerHTMLContent;
    } else {
        console.warn(`Element with ID '${elementId}' not found.`);
    }
}

safeSetInnerHTML("btb_title_1", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 480-537: Passenger Side Door Assembly</h1></div>`);
safeSetInnerHTML("btb_icon_1_1", `<div class="icon-container"><i class="fas fa-chair"></i></div><div class="title-container">Comfort and Accessibility</div><div class="content-container">Passenger side door designed for easy entry and exit.</div>`);
safeSetInnerHTML("btb_icon_1_2", `<div class="icon-container"><i class="fas fa-palette"></i></div><div class="title-container">Luxury Features</div><div class="content-container">Enhanced insulation and comfort reflect modern expectations.</div>`);
safeSetInnerHTML("btb_maintext_1", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this section, we assemble the <strong>passenger side front door</strong>.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">The doors have seen various enhancements over the years, including improved sound insulation and luxury features that cater to modern expectations. The G-Class is often associated with high-profile personalities and has been featured in numerous films and television shows, further embedding it into popular culture as a symbol of luxury and adventure. Its iconic status continues to attract enthusiasts who appreciate both its rugged capabilities and stylish design.</p></div>`);
safeSetInnerHTML("btb_title_2", `<div class="title-container"><h1 style="white-space:pre-wrap;">Bag 12: Front Dashboard Construction</h1></div>`);
safeSetInnerHTML("btb_icon_2_1", `<div class="icon-container"><i class="fas fa-tachometer-alt"></i></div><div class="title-container">Multifunctional Design</div><div class="content-container">The dashboard integrates essential controls and displays for driver convenience.</div>`);
safeSetInnerHTML("btb_icon_2_2", `<div class="icon-container"><i class="fas fa-lightbulb"></i></div><div class="title-container">Evolution of Controls</div><div class="content-container">From analog gauges to digital displays, dashboards have transformed significantly.</div>`);
safeSetInnerHTML("btb_maintext_2", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In Bag 12, we focus on constructing the <strong>front dashboard</strong>, including the dashboard frame and windshield wipers of the G-Class model. The dashboard is a critical component that houses various controls and displays, providing the driver with essential information and functionality for a smooth driving experience.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">The evolution of dashboard controls in vehicles like the G-Class reflects significant advancements in automotive technology. Early models featured basic instrumentation with analog gauges that displayed speed, fuel level, and engine temperature. As technology progressed, dashboards became more sophisticated, integrating digital displays and advanced infotainment systems. The introduction of features such as navigation systems, climate control interfaces, and multimedia connectivity transformed dashboards into multifunctional command centers.</p></div>`);
safeSetInnerHTML("btb_image_2", `<img src="https://github.com/behind-the-builds/btb/g500/images/53678777769_d2eed9548d_o.jpg" alt="2025 G-Class Dashboard">`);
safeSetInnerHTML("btb_caption_2", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">2025 G-Class Dashboard</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://www.flickr.com/photos/artvlive/53678777769/" target="_blank">source</a></p></div>`);
