
function safeSetInnerHTML(elementId, innerHTMLContent) {
    const element = document.getElementById(elementId);
    if (element) {
        element.innerHTML = innerHTMLContent;
    } else {
        console.warn(`Element with ID '${elementId}' not found.`);
    }
}

safeSetInnerHTML("btb_title_1", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 517-537: Dashboard and Wiper Assembly</h1></div>`);
safeSetInnerHTML("btb_icon_1_1", `<div class="icon-container"><i class="fas fa-toolbox"></i></div><div class="title-container">Structural Integrity</div><div class="content-container">The dashboard frame provides stability for various components.</div>`);
safeSetInnerHTML("btb_icon_1_2", `<div class="icon-container"><i class="fas fa-eye"></i></div><div class="title-container">Enhanced Design</div><div class="content-container">Vertical windshield design improves visibility despite aerodynamic trade-offs.</div>`);
safeSetInnerHTML("btb_maintext_1", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this section, we assemble the <strong>front dashboard</strong> along with its frame and windshield wipers.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">The design of the G-Class's vertical windshield contributes to its distinctive aesthetic but also impacts aerodynamics. While a vertical windshield may not be as aerodynamically efficient as a sloped design, it enhances visibility and provides a unique look that has become iconic for the G-Class. This design choice aligns with Mercedes-Benz's philosophy of combining functionality with style, ensuring that even with lower aerodynamic efficiency, drivers enjoy an unparalleled view of their surroundings.</p></div>`);
safeSetInnerHTML("btb_image_1", `<img src="https://github.com/behind-the-builds/btb/g500/images/Mercedes-Benz_G_63_AMG_(W_463,_3._Facelift).jpg" alt="AMG G-63">`);
safeSetInnerHTML("btb_caption_1", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">AMG G-63</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:Mercedes-Benz_G_63_AMG_(W_463,_3._Facelift).jpg" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_2", `<div class="title-container"><h1 style="white-space:pre-wrap;">Bag 13: Front Bumper and Grill Construction</h1></div>`);
safeSetInnerHTML("btb_icon_2_1", `<div class="icon-container"><i class="fas fa-border-all"></i></div><div class="title-container">Iconic Front Grill</div><div class="content-container">The grill enhances airflow while contributing to the vehicle's rugged aesthetics.</div>`);
safeSetInnerHTML("btb_icon_2_2", `<div class="icon-container"><i class="fas fa-history"></i></div><div class="title-container">Tribute to Origins</div><div class="content-container">License plate "S G 1979" signifies the G-Class's rich history.</div>`);
safeSetInnerHTML("btb_maintext_2", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In Bag 13, we focus on constructing the <strong>front bumper</strong> and <strong>grill</strong> of the G-Class model. The grill is not only a key aesthetic feature but also plays a crucial role in engine cooling and airflow. The assembly begins with completing the frame at the base of the windshield, followed by building the front grill and attaching the front bumper.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">A notable detail in this build is the license plate that reads "S G 1979." This plate pays homage to the origins of the Mercedes-Benz G-Class, which was first introduced in 1979. The "S" stands for Stuttgart, Germany, where Mercedes-Benz is headquartered; "G" represents <strong>Gelandewagen</strong>, meaning “terrain vehicle” in German; and "1979" marks the year of its launch. This small yet significant detail captures the essence of the G-Wagon’s heritage.</p></div>`);
safeSetInnerHTML("btb_image_2", `<img src="https://github.com/behind-the-builds/btb/g500/images/1983_Mercedes_280_GE_Paris_Dakar.jpg" alt="1983 Paris-Dakar G-Class">`);
safeSetInnerHTML("btb_caption_2", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">1983 Paris-Dakar G-Class</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:1983_Mercedes_280_GE_Paris_Dakar.jpg" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_3", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 538-569: Front Grill Assembly</h1></div>`);
safeSetInnerHTML("btb_icon_3_1", `<div class="icon-container"><i class="fas fa-palette"></i></div><div class="title-container">Stylish Functionality</div><div class="content-container">The front grill combines protection with aesthetic appeal.</div>`);
safeSetInnerHTML("btb_icon_3_2", `<div class="icon-container"><i class="fas fa-tachometer-alt"></i></div><div class="title-container">Quality Engineering</div><div class="content-container">Designed for durability while enhancing airflow to the engine.</div>`);
safeSetInnerHTML("btb_maintext_3", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this section, we construct the <strong>front grill</strong> of the G-Class model after completing two short steps at the base of the windshield frame. The grill is designed to be both functional and stylish, reflecting Mercedes-Benz's commitment to quality engineering.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">The front grill has evolved over time, adapting to modern design trends while maintaining its iconic look. In earlier models, the grill was more utilitarian, but as luxury features were integrated into newer versions, it became a defining element of the vehicle's front fascia.</p></div>`);
safeSetInnerHTML("btb_image_3", `<img src="https://github.com/behind-the-builds/btb/g500/images/1979_Mercedes-Benz_G-Class.jpg" alt="1979 G-Class">`);
safeSetInnerHTML("btb_caption_3", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">1979 G-Class</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:1979_Mercedes-Benz_G-Class.jpg" target="_blank">source</a></p></div>`);
