
function safeSetInnerHTML(elementId, innerHTMLContent) {
    const element = document.getElementById(elementId);
    if (element) {
        element.innerHTML = innerHTMLContent;
    } else {
        console.warn(`Element with ID '${elementId}' not found.`);
    }
}

safeSetInnerHTML("btb_title_1", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 622-636: Hood Assembly</h1></div>`);
safeSetInnerHTML("btb_icon_1_1", `<div class="icon-container"><i class="fas fa-car"></i></div><div class="title-container">Functional Aesthetics</div><div class="content-container">The hood serves to protect the engine while maintaining the G-Class’s iconic and timeless look.</div>`);
safeSetInnerHTML("btb_icon_1_2", `<div class="icon-container"><i class="fas fa-award"></i></div><div class="title-container">Lasting Appeal</div><div class="content-container">G-Class’s design balance led to exclusive releases, like the G63 AMG 6x6 and G650 Maybach.</div>`);
safeSetInnerHTML("btb_maintext_1", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this final stage of hood assembly, we bring together the central hood panel, completing the engine cover. The hood itself serves both functional and stylistic purposes, protecting the engine from harsh environments while enhancing the G-Class’s recognizable look.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">Despite the G-Class’s iconic status, Mercedes-Benz has carefully balanced updates to meet modern standards while preserving its heritage. The G-Class was revamped in 2018 with a new platform for improved handling, but the exterior—including the hood—remained largely unchanged, preserving the look that enthusiasts love. This combination of timeless design with cutting-edge engineering has contributed to the G-Class’s lasting appeal, leading to special editions and limited releases, such as the G63 AMG 6x6, and even the ultra-exclusive G650 Maybach Landaulet.</p></div>`);
safeSetInnerHTML("btb_image_1", `<img src="https://github.com/behind-the-builds/btb/g500/images/Mercedes-Maybach_G_650_Landaulet_IMG_0753.jpg" alt="G650 Maybach Landaulet">`);
safeSetInnerHTML("btb_caption_1", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">G650 Maybach Landaulet</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:Mercedes-Maybach_G_650_Landaulet_IMG_0753.jpg" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_2", `<div class="title-container"><h1 style="white-space:pre-wrap;">Bag 15: Front Wheel Wells, Headlights, and Rear Bumper</h1></div>`);
safeSetInnerHTML("btb_icon_2_1", `<div class="icon-container"><i class="fas fa-wrench"></i></div><div class="title-container">Functional Design</div><div class="content-container">Designed with off-road adaptability, allowing extra suspension room for smooth operation.</div>`);
safeSetInnerHTML("btb_icon_2_2", `<div class="icon-container"><i class="fas fa-car"></i></div><div class="title-container">Classic G-Class Style</div><div class="content-container">Signature features echo the G-Class’s durable military origins and modern luxury.</div>`);
safeSetInnerHTML("btb_maintext_2", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In Bag 15, we assemble the <strong>front wheel wells</strong>, <strong>headlights</strong>, and <strong>rear bumper</strong> with taillights for our G-Class model. In this LEGO version, the front wheel wells have been designed with extra room to accommodate the suspension’s movement. This adaptation allows the model’s suspension to travel more freely during play, reflecting the off-road capability of the real G-Class.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">The G-Class components, from its boxy headlights to its rugged rear bumper, showcase Mercedes-Benz’s blend of durability and style. Initially developed for military use, the G-Wagen's features are now icons of luxury. These parts stay true to the G-Class aesthetic, bridging its practical roots and upscale evolution.</p></div>`);
safeSetInnerHTML("btb_image_2", `<img src="https://github.com/behind-the-builds/btb/g500/images/Mercedes_G_500.jpg" alt="Mercedes-Benz G500">`);
safeSetInnerHTML("btb_caption_2", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">Mercedes-Benz G500</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:Mercedes_G_500.jpg" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_3", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 637-664: Front Wheel Wells and Headlights</h1></div>`);
safeSetInnerHTML("btb_icon_3_1", `<div class="icon-container"><i class="fas fa-lightbulb"></i></div><div class="title-container">Iconic Headlights</div><div class="content-container">Square headlights have been a defining feature of the G-Class since its launch.</div>`);
safeSetInnerHTML("btb_icon_3_2", `<div class="icon-container"><i class="fas fa-globe"></i></div><div class="title-container">Off-Road Capability</div><div class="content-container">Extra room in wheel wells reflects suspension travel for navigating rugged terrain.</div>`);
safeSetInnerHTML("btb_maintext_3", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this section, we build the <strong>front wheel wells</strong> and <strong>headlights</strong>. The G-Class’s distinctive headlights have remained a defining feature since the vehicle’s debut. When the G-Class was redesigned in 2018, Mercedes-Benz preserved the headlight shape, symbolizing its rugged heritage and timeless appeal.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">The headlights were initially all about durability, built to withstand rough conditions. With technological upgrades, they now incorporate advanced lighting without losing their iconic shape. The LEGO model’s raised wheel wells also allow more suspension travel, echoing the G-Class’s off-road resilience and adapting it for play.</p></div>`);
safeSetInnerHTML("btb_image_3", `<img src="https://github.com/behind-the-builds/btb/g500/images/G_500_exterior,_silver_(Mercedes-Benz)_left_side,_exterior,_front.jpg" alt="G500 front headlight">`);
safeSetInnerHTML("btb_caption_3", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">G500 front headlight</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:G_500_exterior,_silver_(Mercedes-Benz)_left_side,_exterior,_front.jpg" target="_blank">source</a></p></div>`);
