
function safeSetInnerHTML(elementId, innerHTMLContent) {
    const element = document.getElementById(elementId);
    if (element) {
        element.innerHTML = innerHTMLContent;
    } else {
        console.warn(`Element with ID '${elementId}' not found.`);
    }
}

safeSetInnerHTML("btb_title_1", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 570-586: Front Bumper Assembly</h1></div>`);
safeSetInnerHTML("btb_icon_1_1", `<div class="icon-container"><i class="fas fa-tachometer-alt"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_icon_1_2", `<div class="icon-container"><i class="fas fa-shield-alt"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_maintext_1", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this section, we assemble and attach the <strong>front bumper</strong> to complete this segment of the build. The bumper is designed to absorb impacts while providing a rugged look that complements the overall design of the G-Class.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">The front bumper has seen significant advancements since its introduction. Originally designed for basic protection, modern bumpers incorporate advanced materials and designs that enhance safety without compromising style. The integration of features like fog lights and winch mounts has made it a versatile component for both urban driving and off-road excursions.</p></div>`);
safeSetInnerHTML("btb_image_1", `<img src="https://github.com/behind-the-builds/btb/g500/images/Mercedes-Benz_W460_250_GD_IMG_4536.jpg" alt="W460 G-Class showcasing its rugged design.">`);
safeSetInnerHTML("btb_caption_1", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">W460 G-Class showcasing its rugged design.</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:Mercedes-Benz_W460_250_GD_IMG_4536.jpg" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_2", `<div class="title-container"><h1 style="white-space:pre-wrap;">Bag 14: Hood Construction</h1></div>`);
safeSetInnerHTML("btb_icon_2_1", `<div class="icon-container"><i class="fas fa-arrows-alt"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_icon_2_2", `<div class="icon-container"><i class="fas fa-wrench"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_maintext_2", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In Bag 14, we build the <strong>working hood</strong> of the G-Class model. The hinge mechanism is essential for allowing the hood to open and close smoothly, providing access to the engine compartment.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">An interesting aspect of the G-Class's history is its use in various humanitarian missions. In the 1990s, the G-Class was utilized by organizations such as the Red Cross and UN peacekeeping forces in conflict zones due to its reliability and off-road capabilities. This reputation for resilience has made it a preferred choice for those needing a dependable vehicle in challenging environments.</p></div>`);
safeSetInnerHTML("btb_image_2", `<img src="https://github.com/behind-the-builds/btb/g500/images/Mercedes-Benz_G-Class_(17146029221).jpg" alt="A UN G-Class">`);
safeSetInnerHTML("btb_caption_2", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">A UN G-Class</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:Mercedes-Benz_G-Class_(17146029221).jpg" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_3", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 587-590: Hinge Mechanism Assembly</h1></div>`);
safeSetInnerHTML("btb_icon_3_1", `<div class="icon-container"><i class="fas fa-medkit"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_icon_3_2", `<div class="icon-container"><i class="fas fa-wrench"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_maintext_3", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this section, we assemble the <strong>hinge mechanism</strong> that allows the G-Class’s hood to open smoothly, providing easy access to the engine compartment. Hinge mechanisms may seem straightforward, but in vehicles built for rugged use, they must balance durability with ease of operation.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">The development of the G-Class began in <strong>1972-1973</strong>, when Mercedes-Benz, in collaboration with Steyr-Daimler-Puch, designed it for military needs, prioritizing durability across all components. After years of testing and refinement, the vehicle officially launched in <strong>1979</strong>. Even as the model evolved into a luxury vehicle, its core design, including features like the hood and hinges, retained a rugged quality. The G-Class became iconic not only for its capability but also for its style, earning fans like Pope John Paul II, who chose a G-Wagen as his Popemobile in the early 1980s.</p></div>`);
safeSetInnerHTML("btb_image_3", `<img src="https://github.com/behind-the-builds/btb/g500/images/Luxembourg,_visite_officielle_Pape_François_26.09.2024_(128).jpg" alt="G500 Popemobile in Luxembourg">`);
safeSetInnerHTML("btb_caption_3", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">G500 Popemobile in Luxembourg</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:Luxembourg,_visite_officielle_Pape_Fran%C3%A7ois_26.09.2024_(128).jpg" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_4", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 591-621: Hood Sides Assembly</h1></div>`);
safeSetInnerHTML("btb_icon_4_1", `<div class="icon-container"><i class="fas fa-clock"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_icon_4_2", `<div class="icon-container"><i class="fas fa-car"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_maintext_4", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this phase, we assemble the <strong>sides of the hood</strong>, which help frame the engine compartment above the wheel wells. The G-Class's angular hood design is part of its iconic profile, emphasizing straight lines and flat surfaces. These features, originally intended to simplify manufacturing and reinforce strength, became a hallmark of the G-Class’s aesthetic appeal.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">From a design perspective, the G-Class has remained virtually unchanged since its debut in 1979. This boxy, utilitarian look was essential in off-road conditions, but it has also helped the G-Class endure as a symbol of rugged elegance in the luxury market. The side panels of the hood, like much of the vehicle, have seen minor refinements to improve aerodynamics, yet the fundamental silhouette and sturdy construction endure, a testament to the “form follows function” ethos that shaped the original model.</p></div>`);
safeSetInnerHTML("btb_image_4", `<img src="https://github.com/behind-the-builds/btb/g500/images/Blue_Mercedes_G_55_AMG,_Berlin.jpg" alt="G55 AMG in Berlin">`);
safeSetInnerHTML("btb_caption_4", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">G55 AMG in Berlin</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:Blue_Mercedes_G_55_AMG,_Berlin.jpg" target="_blank">source</a></p></div>`);
