
function safeSetInnerHTML(elementId, innerHTMLContent) {
    const element = document.getElementById(elementId);
    if (element) {
        element.innerHTML = innerHTMLContent;
    } else {
        console.warn(`Element with ID '${elementId}' not found.`);
    }
}

safeSetInnerHTML("btb_title_1", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 740-756: Tailgate Assembly</h1></div>`);
safeSetInnerHTML("btb_icon_1_1", `<div class="icon-container"><i class="fas fa-tools"></i></div><div class="title-container">Heavy-Duty Tailgate</div><div class="content-container">The tailgate is built for durability, supporting essential tasks in rugged environments.</div>`);
safeSetInnerHTML("btb_icon_1_2", `<div class="icon-container"><i class="fas fa-compass"></i></div><div class="title-container">Mission-Ready Access</div><div class="content-container">Ensures quick cargo access, valuable for rescue and special operations teams.</div>`);
safeSetInnerHTML("btb_maintext_1", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this stage, we complete the <strong>rear tailgate assembly</strong>, designed for durability and frequent access to the rear cargo area. Known for its robust construction, the G-Class’s tailgate is built to withstand heavy-duty use in off-road and mission scenarios. The tailgate’s functionality has proven essential for various military and rescue operations, where quick and reliable cargo access is critical.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">The G-Class’s tailgate has supported rescue teams and special operations worldwide, enabling easy transport of essential gear. Whether in mountainous terrains or during flood rescues, the tailgate design reflects the G-Class’s legacy of utility and resilience.</p></div>`);
safeSetInnerHTML("btb_image_1", `<img src="https://github.com/behind-the-builds/btb/g500/images/KOCR_LUVW01.JPG" alt="G-Class serving in wet conditions">`);
safeSetInnerHTML("btb_caption_1", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">G-Class serving in wet conditions</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:KOCR_LUVW01.JPG" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_2", `<div class="title-container"><h1 style="white-space:pre-wrap;">Bag 18: Roof Assembly</h1></div>`);
safeSetInnerHTML("btb_icon_2_1", `<div class="icon-container"><i class="fas fa-globe"></i></div><div class="title-container">High Load-Bearing Roof</div><div class="content-container">Supports up to 150 kg, ideal for roof racks and equipment on rugged journeys.</div>`);
safeSetInnerHTML("btb_icon_2_2", `<div class="icon-container"><i class="fas fa-hammer"></i></div><div class="title-container">Reinforced Durability</div><div class="content-container">Made with laser-welded steel, balancing strength and weight for off-road stability.</div>`);
safeSetInnerHTML("btb_maintext_2", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In Bag 18, we assemble the <strong>roof</strong> of our G-Class model. Known for its strength, the G-Class roof can support up to <strong>150 kg</strong> (330 lbs), making it ideal for roof racks, gear, or tents. Since 2019, Mercedes has used high-strength steel and <strong>laser-welded joints</strong>, enhancing both durability and stability while also reducing weight. This construction ensures that the roof can withstand off-road conditions and adds to the G-Class’s rugged reputation.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">The G-Class’s boxy roof design not only maximizes interior space but also reflects its military origins. Reinforced with ultra-high-strength steel, the roof has been further adapted for armoring in some variants, meeting the needs of high-security or expedition applications. This combination of utility and strength has helped the G-Class stand the test of time, becoming one of the most iconic off-road vehicles.</p></div>`);
safeSetInnerHTML("btb_image_2", `<img src="https://github.com/behind-the-builds/btb/g500/images/153434948_f5a05344bb_o.jpg" alt="Canadian Armed Forces G-Class with loaded roof rack">`);
safeSetInnerHTML("btb_caption_2", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">Canadian Armed Forces G-Class with loaded roof rack</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://www.flickr.com/photos/squeakymarmot/153434948" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_3", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 757-789: Roof Assembly</h1></div>`);
safeSetInnerHTML("btb_icon_3_1", `<div class="icon-container"><i class="fas fa-shield-alt"></i></div><div class="title-container">Military-Grade Strength</div><div class="content-container">Engineered to support both expedition gear and armored configurations for high-security use.</div>`);
safeSetInnerHTML("btb_icon_3_2", `<div class="icon-container"><i class="fas fa-layer-group"></i></div><div class="title-container">Laser-Welded Joints</div><div class="content-container">Laser welding enhances durability and reduces weight for a stable, rugged roof design.</div>`);
safeSetInnerHTML("btb_maintext_3", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this phase, we complete the <strong>roof assembly</strong>. Built for strength, the G-Class roof uses laser-welded, high-strength steel, providing a sturdy foundation for carrying gear and withstanding impacts. This structural strength aligns with the G-Class’s rugged capabilities, allowing it to perform reliably in demanding conditions. The roof’s durability also supports armored variants that meet military-grade standards, enhancing its role in high-security and adventure applications.</p></div>`);
safeSetInnerHTML("btb_image_3", `<img src="https://github.com/behind-the-builds/btb/g500/images/Terrängbil_5_Revinge_2015-1.jpg" alt="A military G-Class outfitted for off-road conditions">`);
safeSetInnerHTML("btb_caption_3", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">A military G-Class outfitted for off-road conditions</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:Terr%C3%A4ngbil_5_Revinge_2015-1.jpg" target="_blank">source</a></p></div>`);
