
function safeSetInnerHTML(elementId, innerHTMLContent) {
    const element = document.getElementById(elementId);
    if (element) {
        element.innerHTML = innerHTMLContent;
    } else {
        console.warn(`Element with ID '${elementId}' not found.`);
    }
}

safeSetInnerHTML("btb_title_1", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 20-31: Steering System</h1></div>`);
safeSetInnerHTML("btb_icon_1_1", `<div class="icon-container"><i class="fas fa-cog"></i></div><div class="title-container">Steering Evolution</div><div class="content-container">G-Class transitioned from recirculating ball to rack and pinion steering in 2019, improving on-road handling.</div>`);
safeSetInnerHTML("btb_icon_1_2", `<div class="icon-container"><i class="fas fa-car"></i></div><div class="title-container">Off-Road to On-Road</div><div class="content-container">The new steering system balances the G-Class's legendary off-road prowess with improved everyday drivability.</div>`);
safeSetInnerHTML("btb_maintext_1", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this stage, we assemble the <strong>steering mechanism</strong> of our G-Class model. The G-Wagen's <strong>steering system</strong> has undergone significant changes over its long production history. For decades, the G-Class utilized a <strong>recirculating ball steering system</strong>, known for its durability and ability to handle heavy loads. This system was particularly well-suited to off-road use, providing good feedback and reliability in rugged conditions.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">However, with the <strong>2019 redesign</strong>, Mercedes-Benz made a significant change by switching to a <strong>rack and pinion steering system</strong>. This transition aimed to improve <strong>on-road handling</strong> and provide a more precise steering feel. Rack and pinion systems generally offer more direct steering response and better road feedback, enhancing the G-Class's performance on paved roads without compromising its off-road capabilities.</p></div>`);
safeSetInnerHTML("btb_image_1", `<img src="https://github.com/behind-the-builds/btb/g500/images/RecirculatingBall.png" alt="Recirculating ball steering system">`);
safeSetInnerHTML("btb_caption_1", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">Recirculating ball steering system</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:RecirculatingBall.png" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_2", `<div class="title-container"><h1 style="white-space:pre-wrap;">Bag 2: Steering and Engine Assembly</h1></div>`);
safeSetInnerHTML("btb_icon_2_1", `<div class="icon-container"><i class="fas fa-tachometer-alt"></i></div><div class="title-container">Iconic V8 Engine</div><div class="content-container">The G500 traditionally features a powerful 4.0-liter twin-turbo V8.</div>`);
safeSetInnerHTML("btb_icon_2_2", `<div class="icon-container"><i class="fas fa-cogs"></i></div><div class="title-container">Compact Inline-Six Model</div><div class="content-container">The new inline-six engine allows for a compact and efficient design.</div>`);
safeSetInnerHTML("btb_maintext_2", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">The <strong>Mercedes-Benz G500</strong> engine is known for its robust power and off-road capability. Traditionally, the G500 has been equipped with a <strong>4.0-liter twin-turbo V8</strong> engine, delivering impressive power for both on-road and off-road performance. This V8 configuration has been a hallmark of the G-Class, providing the torque and durability necessary to navigate difficult terrains with ease.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">However, starting with the 2025 model year, the G500 has transitioned to a <strong>turbocharged 3.0-liter inline-six engine</strong>, which offers enhanced performance and efficiency while maintaining the vehicle's legendary capabilities.</p></div>`);
safeSetInnerHTML("btb_image_2", `<img src="https://github.com/behind-the-builds/btb/g500/images/G_500_exterior,_silver_(Mercedes-Benz)_left_side,_exterior,_V8_logo_Mercedes-Benz.jpg" alt="V8 logo on a G500">`);
safeSetInnerHTML("btb_caption_2", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">V8 logo on a G500</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:G_500_exterior,_silver_(Mercedes-Benz)_left_side,_exterior,_V8_logo_Mercedes-Benz.jpg" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_3", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 32-51: Steering System</h1></div>`);
safeSetInnerHTML("btb_icon_3_1", `<div class="icon-container"><i class="fas fa-cogs"></i></div><div class="title-container">Ackermann Steering</div><div class="content-container">Advanced geometry reduces tire wear and improves handling in tight turns.</div>`);
safeSetInnerHTML("btb_icon_3_2", `<div class="icon-container"><i class="fas fa-globe"></i></div><div class="title-container">Off-Road Precision</div><div class="content-container">Enhances maneuverability on rugged terrain, crucial for the G-Class's capabilities.</div>`);
safeSetInnerHTML("btb_maintext_3", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In these instructions, we build the functional steering system of the model which, impressively for a LEGO model, incorporates <strong>Ackermann steering geometry</strong>. This design principle, used in almost all real vehicles, ensures that the inner wheel turns at a sharper angle than the outer wheel during cornering.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">Ackermann steering geometry provides several benefits in full-size vehicles. It reduces tire scrub during turns, which decreases wear and improves handling, especially at lower speeds and in tight spaces. For off-road vehicles like the G-Class, this steering design enhances maneuverability on rugged terrain, allowing for precise navigation around obstacles.</p></div>`);
safeSetInnerHTML("btb_image_3", `<img src="https://github.com/behind-the-builds/btb/g500/images/Ackermann.jpg" alt="Diagram of Ackermann steering principle">`);
safeSetInnerHTML("btb_caption_3", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">Diagram of Ackermann steering principle</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:Ackermann.svg" target="_blank">source</a></p></div>`);
