
function safeSetInnerHTML(elementId, innerHTMLContent) {
    const element = document.getElementById(elementId);
    if (element) {
        element.innerHTML = innerHTMLContent;
    } else {
        console.warn(`Element with ID '${elementId}' not found.`);
    }
}

safeSetInnerHTML("btb_title_1", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 52-93: Engine Housing and Pistons</h1></div>`);
safeSetInnerHTML("btb_icon_1_1", `<div class="icon-container"><i class="fas fa-globe"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_icon_1_2", `<div class="icon-container"><i class="fas fa-wrench"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_maintext_1", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this part of the build, we assemble the <strong>engine housing</strong> and the <strong>working pistons</strong> of the model’s engine. The real Mercedes-Benz G500 has transitioned to a <strong>turbocharged 3.0-liter inline-six engine</strong> for the 2025 model year, emphasizing both power and efficiency in a compact design.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">Mercedes-Benz has historically used both <strong>V-type and inline engines</strong> in its lineup, with V engines, such as the V6 and V8, becoming increasingly popular for their space efficiency and power. Unlike inline engines, which align cylinders in a single row, the <strong>V configuration</strong> arranges cylinders in two angled rows, creating a “V” shape. This design keeps the engine shorter in length and lower in height, optimizing it for a lower center of gravity and efficient packaging.</p></div>`);
safeSetInnerHTML("btb_image_1", `<img src="https://github.com/behind-the-builds/btb/g500/images/V-engine.gif" alt="Diagram of a V-type engine">`);
safeSetInnerHTML("btb_caption_1", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">Diagram of a V-type engine</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:V-engine.gif" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_2", `<div class="title-container"><h1 style="white-space:pre-wrap;">Bag 3: Center Differential and Gearbox</h1></div>`);
safeSetInnerHTML("btb_icon_2_1", `<div class="icon-container"><i class="fas fa-car"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_icon_2_2", `<div class="icon-container"><i class="fas fa-exchange-alt"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_maintext_2", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In <strong>Bag 3</strong>, we assemble the <strong>center differential</strong> and <strong>gearbox</strong> of the G500 model, both crucial elements that manage power distribution and vehicle control. The <strong>center differential</strong> plays a key role in the G-Class's legendary off-road ability by dividing engine power between the front and rear axles, allowing wheels to rotate at different speeds. This capability is essential when navigating uneven terrain, as it prevents wheel slippage and ensures that traction is maintained across all four wheels.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">The <strong>gearbox</strong>, or transmission, manages the engine's power output to provide the right balance of speed and torque for each driving situation. In the G-Class, the transmission is engineered for versatility, providing low-range gears for off-road power and high-range gears for efficient highway cruising. Together, the center differential and gearbox allow the G500 to adapt to a wide variety of terrains and conditions, balancing power and control in any environment.</p></div>`);
safeSetInnerHTML("btb_title_3", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 94-119: Center Differential</h1></div>`);
safeSetInnerHTML("btb_icon_3_1", `<div class="icon-container"><i class="fas fa-tachometer-alt"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_icon_3_2", `<div class="icon-container"><i class="fas fa-wrench"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_maintext_3", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In <strong>Instructions 94-119</strong>, we build the <strong>center differential</strong>, which helps manage power between the front and rear axles, a key feature of the G-Class's off-road stability. The G-Class introduced its <strong>triple-locking differential system</strong> in the late 1980s with the W463 model, setting a standard in off-road capability. This advanced feature allows drivers to lock the center, rear, and front differentials independently, providing exceptional traction in extreme conditions....</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">This system remains one of the defining elements of the G-Class's design, solidifying its reputation as one of the most capable luxury off-road vehicles available.</p></div>`);
safeSetInnerHTML("btb_title_4", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 120-134: Transmission</h1></div>`);
safeSetInnerHTML("btb_icon_4_1", `<div class="icon-container"><i class="fas fa-lock"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_icon_4_2", `<div class="icon-container"><i class="fas fa-cogs"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_maintext_4", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In <strong>Instructions 120-134</strong>, we build the first part of the <strong>transmission</strong>, a crucial system responsible for transferring power from the engine to the wheels. In the G-Class, the transmission is designed to handle both on-road cruising and rigorous off-road demands. It uses multiple gear ratios to balance torque and speed, which is essential for a vehicle that needs to perform reliably on highways as well as rugged trails.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">The G500's transmission includes a <strong>low-range mode</strong>, activated for challenging off-road conditions, providing greater torque to handle steep inclines and uneven terrain. This versatility is a hallmark of the G-Class, enabling it to adapt seamlessly to both luxury driving and intense off-road scenarios.</p></div>`);
safeSetInnerHTML("btb_title_5", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instr. 134-154: Transmission Completion & Engine Connection</h1></div>`);
safeSetInnerHTML("btb_icon_5_1", `<div class="icon-container"><i class="fas fa-globe"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_icon_5_2", `<div class="icon-container"><i class="fas fa-car"></i></div><div class="title-container"></div><div class="content-container"></div>`);
safeSetInnerHTML("btb_maintext_5", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In <strong>Instructions 134-154</strong>, we complete the <strong>transmission system</strong> and attach it to the engine. Early G-Class models were available with manual transmissions, but with the introduction of the W463 model in the late 1980s, Mercedes-Benz transitioned to <strong>automatic transmissions</strong> to enhance driving comfort.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">Modern G500 models now feature a <strong>9-speed automatic transmission</strong>, providing smooth shifts across a wide range of gear ratios. This allows for efficient highway cruising in higher gears while maintaining strong torque in low-range settings for off-road challenges.</p></div>`);
safeSetInnerHTML("btb_image_5", `<img src="https://github.com/behind-the-builds/btb/g500/images/G55_Schöckl_2009.jpg" alt="Two class G-class wagons in Austria">`);
safeSetInnerHTML("btb_caption_5", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">Two class G-class wagons in Austria</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:G55_%2B_G_%2B_Sch%C3%B6ckl,_2009.JPG" target="_blank">source</a></p></div>`);
