
function safeSetInnerHTML(elementId, innerHTMLContent) {
    const element = document.getElementById(elementId);
    if (element) {
        element.innerHTML = innerHTMLContent;
    } else {
        console.warn(`Element with ID '${elementId}' not found.`);
    }
}

safeSetInnerHTML("btb_title_1", `<div class="title-container"><h1 style="white-space:pre-wrap;">Bag 5: Undercarriage and Rigid Axle Suspension</h1></div>`);
safeSetInnerHTML("btb_icon_1_1", `<div class="icon-container"><i class="fas fa-truck"></i></div><div class="title-container">Rigid Axle Design</div><div class="content-container">Non-independent suspension provides strength and durability for off-road conditions.</div>`);
safeSetInnerHTML("btb_icon_1_2", `<div class="icon-container"><i class="fas fa-globe"></i></div><div class="title-container">Enhanced Traction</div><div class="content-container">Rigid axles ensure both wheels maintain ground contact, improving stability on rough terrain.</div>`);
safeSetInnerHTML("btb_maintext_1", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this section, we extend the undercarriage structure to the rear axle, laying the groundwork for a robust and functional model. This step is crucial as it provides the necessary support for the vehicle's drivetrain and suspension systems.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">We begin constructing the <strong>rigid axle suspension</strong>, which is a non-independent suspension system commonly found in off-road vehicles like the G-Class. This type of suspension connects both rear wheels via a solid axle, allowing them to move together. While this design may limit individual wheel movement compared to independent systems, it offers significant advantages in durability and strength, especially in rugged terrains.</p></div>`);
safeSetInnerHTML("btb_image_1", `<img src="https://github.com/behind-the-builds/btb/g500/images/21196907634_9ba9e8e28c_o.jpg" alt="G500 from the rear, showcasing its robust undercarriage design.">`);
safeSetInnerHTML("btb_caption_1", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">G500 from the rear, showcasing its robust undercarriage design.</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://www.flickr.com/photos/klimenko/21196907634/" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_2", `<div class="title-container"><h1 style="white-space:pre-wrap;">Bag 6: Rear Drivetrain Completion and Wheel Assembly</h1></div>`);
safeSetInnerHTML("btb_icon_2_1", `<div class="icon-container"><i class="fas fa-cog"></i></div><div class="title-container">Rear Drivetrain</div><div class="content-container">Completes power transmission to rear wheels for realistic movement.</div>`);
safeSetInnerHTML("btb_icon_2_2", `<div class="icon-container"><i class="fas fa-cogs"></i></div><div class="title-container">Steering Control</div><div class="content-container">Adding a steering wheel enhances interactive features and control.</div>`);
safeSetInnerHTML("btb_icon_2_3", `<div class="icon-container"><i class="fas fa-circle"></i></div><div class="title-container">Off-Road Wheels</div><div class="content-container">Tires designed for stability and traction on various terrains.</div>`);
safeSetInnerHTML("btb_maintext_2", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this section, we complete the <strong>rear drivetrain</strong>, ensuring that power is effectively transmitted to the rear wheels.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">Next, we add the <strong>steering wheel</strong> to enhance the model's interactive features. The steering wheel connects to the steering system we built earlier, allowing for smooth maneuvering of the vehicle.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">Finally, we put on the <strong>wheels and tires</strong>, completing the assembly of the G-Class model. The wheels are designed to replicate the iconic look of the G-Class while providing stability and traction. The tires are crafted to mimic off-road capabilities, ensuring that the model can navigate various terrains with ease.</p></div>`);
safeSetInnerHTML("btb_image_2", `<img src="https://github.com/behind-the-builds/btb/g500/images/Mercedes-Benz_G-Class_G300CDI_W461_Swiss_Army_1.jpg" alt="Swiss Army G-Class variant showcasing its rugged design and capabilities.">`);
safeSetInnerHTML("btb_caption_2", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">Swiss Army G-Class variant showcasing its rugged design and capabilities.</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:Mercedes-Benz_G-Class_G300CDI_W461_Swiss_Army_1.png" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_3", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 241-251: Rear Locking Differential</h1></div>`);
safeSetInnerHTML("btb_icon_3_1", `<div class="icon-container"><i class="fas fa-lock"></i></div><div class="title-container">Functional Locking Ability</div><div class="content-container">Engages both rear wheels for improved traction in challenging conditions.</div>`);
safeSetInnerHTML("btb_icon_3_2", `<div class="icon-container"><i class="fas fa-trophy"></i></div><div class="title-container">Rally Heritage</div><div class="content-container">The G-Class's performance in events like the Moroccan Rally showcases its off-road capabilities.</div>`);
safeSetInnerHTML("btb_maintext_3", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this section, we focus on the <strong>rear locking differential</strong>, which features functional locking ability. This differential allows both rear wheels to rotate at the same speed when engaged, providing essential traction in challenging off-road conditions. The ability to lock the rear differential is particularly beneficial when navigating slippery or uneven terrain, ensuring that power is effectively distributed to both wheels.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">The G-Class has a storied history as a capable off-road vehicle, famously participating in events like the <strong>Moroccan Rally</strong>. Its robust design and advanced features, including the rear locking differential, have made it a favorite among rally drivers and off-road enthusiasts alike. The vehicle's ability to tackle extreme conditions has solidified its reputation as not just a luxury SUV but also a formidable competitor in rally racing.</p></div>`);
safeSetInnerHTML("btb_image_3", `<img src="https://github.com/behind-the-builds/btb/g500/images/52549189710_6f9f3ceabb_o.jpg" alt="A rally-ready G500 showcasing its off-road capabilities.">`);
safeSetInnerHTML("btb_caption_3", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">A rally-ready G500 showcasing its off-road capabilities.</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://www.flickr.com/photos/thomas_vogt/52549189710/" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_4", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instr. 252-275: Rigid Rear Axle & Rear Suspension Connection</h1></div>`);
safeSetInnerHTML("btb_icon_4_1", `<div class="icon-container"><i class="fas fa-truck"></i></div><div class="title-container">Rigid Axle Benefits</div><div class="content-container">Provides strength and durability for off-road performance.</div>`);
safeSetInnerHTML("btb_icon_4_2", `<div class="icon-container"><i class="fas fa-globe"></i></div><div class="title-container">Enhanced Traction</div><div class="content-container">Keeps both wheels in contact with the ground for improved stability on uneven surfaces.</div>`);
safeSetInnerHTML("btb_maintext_4", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this section, we build out the <strong>rigid rear axle</strong> and connect it to the rear suspension system. The rigid axle design is a key feature in off-road vehicles like the G-Class, providing several advantages that enhance performance in challenging environments.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">A <strong>rigid rear axle</strong> connects both rear wheels directly, allowing them to move together as a single unit. This setup offers improved durability and strength, making it ideal for off-road conditions where obstacles and uneven surfaces are common. By ensuring that both wheels maintain contact with the ground, a rigid axle enhances traction and stability, which is crucial when navigating rugged terrain.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">Additionally, the simplicity of a rigid axle design means fewer moving parts compared to independent suspension systems, leading to increased reliability and ease of maintenance. This makes the G-Class not only a luxurious vehicle but also a robust performer capable of tackling extreme conditions.</p></div>`);
safeSetInnerHTML("btb_title_5", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 276-281: Steering Wheel and Column</h1></div>`);
safeSetInnerHTML("btb_icon_5_1", `<div class="icon-container"><i class="fas fa-clock"></i></div><div class="title-container">Evolution of Design</div><div class="content-container">From military utility to luxury refinement, the steering wheel reflects the G-Class's heritage.</div>`);
safeSetInnerHTML("btb_maintext_5", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">The <strong>Mercedes-Benz G-Class</strong>, originally developed as a military vehicle in the 1970s, has evolved significantly over the decades. The steering wheel has also seen changes reflecting this evolution—from a utilitarian design in early military models to the more refined and ergonomic options found in modern luxury versions. The G-Class is known for its commanding driving position, which provides excellent visibility and control, essential for navigating challenging terrains.</p></div>`);
safeSetInnerHTML("btb_image_5", `<img src="https://github.com/behind-the-builds/btb/g500/images/Mercedes-Benz_Geländewagen_Norwegian_miltary_MB240GD_int.jpg" alt="Interior of a Norwegian military G-Class showcasing its functional design.">`);
safeSetInnerHTML("btb_caption_5", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">Interior of a Norwegian military G-Class showcasing its functional design.</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:Mercedes-Benz_Gel%C3%A4ndewagen_Norwegian_miltary_MB240GD_int.jpg" target="_blank">source</a></p></div>`);
