
function safeSetInnerHTML(elementId, innerHTMLContent) {
    const element = document.getElementById(elementId);
    if (element) {
        element.innerHTML = innerHTMLContent;
    } else {
        console.warn(`Element with ID '${elementId}' not found.`);
    }
}

safeSetInnerHTML("btb_title_1", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 328-340: Rear Seat Assembly</h1></div>`);
safeSetInnerHTML("btb_icon_1_1", `<div class="icon-container"><i class="fas fa-chair"></i></div><div class="title-container">Versatile Seating</div><div class="content-container">Rear seats can fold down to increase cargo space.</div>`);
safeSetInnerHTML("btb_icon_1_2", `<div class="icon-container"><i class="fas fa-smile"></i></div><div class="title-container">Enhanced Passenger Experience</div><div class="content-container">Modern models feature ergonomic designs for passenger comfort.</div>`);
safeSetInnerHTML("btb_maintext_1", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this section, we assemble the <strong>rear seats</strong> of the LEGO model. The G-Class is known for its spacious interior, which allows for comfortable seating for passengers while maintaining ample cargo space when needed. The ability to fold down the rear seats is a key feature that enhances this versatility.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">Historically, the G-Class has offered various seating configurations to meet different user needs. In modern models, such as those from the <strong>2025 Professional Line</strong>, rear seats are designed with high-quality materials and ergonomic support, ensuring that passengers enjoy a comfortable ride whether on city streets or rugged off-road trails.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">The folding mechanism in this LEGO model replicates the functionality found in real G-Class vehicles, allowing you to maximize cargo space when necessary.</p></div>`);
safeSetInnerHTML("btb_image_1", `<img src="https://github.com/behind-the-builds/btb/g500/images/Mercedes-Benz_G-Class_6x6_JPN_009.JPG" alt="Modern G-Class rear interior showcasing its luxurious features.">`);
safeSetInnerHTML("btb_caption_1", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">Modern G-Class rear interior showcasing its luxurious features.</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:Mercedes-Benz_G-Class_6x6_JPN_009.JPG" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_2", `<div class="title-container"><h1 style="white-space:pre-wrap;">Bag 9: Rear Doors Construction</h1></div>`);
safeSetInnerHTML("btb_icon_2_1", `<div class="icon-container"><i class="fas fa-palette"></i></div><div class="title-container">Copper Orange</div><div class="content-container">Special color option for the 2025 Professional Line enhances aesthetic appeal.</div>`);
safeSetInnerHTML("btb_maintext_2", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In Bag 9, we construct the <strong>fully functional rear doors</strong> of the G-Class model. These doors are the first components of the model to feature the <strong>copper orange</strong> color, which is a special option available for the <strong>2025 Professional Line</strong> of the G-Class. This vibrant color not only enhances the vehicle's aesthetic appeal but also signifies its unique identity within the G-Class lineup.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">The use of copper orange began with the introduction of the Professional Line, which aimed to offer a more rugged and distinctive look while maintaining the luxury and functionality that Mercedes-Benz is known for. This color choice reflects a blend of modern design sensibilities and traditional off-road capability, making it a standout feature for those seeking both style and performance.</p></div>`);
safeSetInnerHTML("btb_image_2", `<img src="https://github.com/behind-the-builds/btb/g500/images/Mercedes-Benz_W_463_(2018)_Professional_Line_IAA_2021_1X7A0207.jpg" alt="2018 G-Class Pro Line">`);
safeSetInnerHTML("btb_caption_2", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">2018 G-Class Pro Line</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:Mercedes-Benz_W_463_(2018)_Professional_Line_IAA_2021_1X7A0207.jpg" target="_blank">source</a></p></div>`);
safeSetInnerHTML("btb_title_3", `<div class="title-container"><h1 style="white-space:pre-wrap;">Instructions 361-388: Driver's Side Door Assembly</h1></div>`);
safeSetInnerHTML("btb_icon_3_1", `<div class="icon-container"><i class="fas fa-clock"></i></div><div class="title-container">Military Durability</div><div class="content-container">Built to withstand impacts and harsh conditions from military origins.</div>`);
safeSetInnerHTML("btb_maintext_3", `<div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">In this section, we focus on assembling the <strong>driver's side rear door</strong>. The inclusion of a fully functional door mechanism in this LEGO model replicates the real vehicle’s attention to detail.</p></div><div class="maintext-container"><p class="sqsrte-large" style="white-space:pre-wrap;">Historically, G-Class doors have been built to withstand harsh conditions, reflecting their military origins. The robust construction ensures that they can handle impacts and maintain integrity during off-road adventures.</p></div>`);
safeSetInnerHTML("btb_image_3", `<img src="https://github.com/behind-the-builds/btb/g500/images/Mercedes_Benz_G-Class_Timboektoe-1.jpg" alt="G-Class in Timbuktu, Mali">`);
safeSetInnerHTML("btb_caption_3", `<div class="caption-container"><p class="sqsrte-large" style="white-space:pre-wrap;">G-Class in Timbuktu, Mali</p></div><div class="source-container"><p class="sqsrte-large" style="white-space:pre-wrap;"><a href="https://commons.wikimedia.org/wiki/File:Mercedes_Benz_G-Class_Timboektoe-1.jpg" target="_blank">source</a></p></div>`);
